# Generated by Django 4.1.5 on 2023-06-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareDetails',
            fields=[
                ('healthcare_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('healthcarenumber', models.BigIntegerField(unique=True)),
                ('physician', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_healthcare', to='api_app.patient')),
            ],
        ),
    ]
